# Site settings
title: Roger's portfolio
description: A simple portfolio from a simple web developer enthusiast
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Roger Souza
user_description: Computer engineer student, pythonist and web development lover.
user_title: Software Developer
email: rogersec42@gmail.com
linkedin_username: roger-souza
github_username:  rogersec
facebook_username: roger.souza.73307

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
